# Generated by Django 3.1.2 on 2021-05-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=50, verbose_name='Ангилалын нэр')),
            ],
            options={
                'verbose_name': 'Ангилал',
                'verbose_name_plural': 'Ангилал',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(max_length=50, verbose_name='Компаний нэр')),
                ('hayag', models.CharField(max_length=150, verbose_name='Компаний хаяг')),
                ('phone', models.CharField(max_length=30, verbose_name='Компаний утас')),
            ],
            options={
                'verbose_name': 'Компани',
                'verbose_name_plural': 'Компани',
            },
        ),
        migrations.CreateModel(
            name='ProdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, verbose_name='Төрлийн нэр')),
            ],
            options={
                'verbose_name': 'Барааны төрөл',
                'verbose_name_plural': 'Барааны төрөл',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=50, verbose_name='Төлөвийн нэр')),
            ],
            options={
                'verbose_name': 'Барааны төлөв',
                'verbose_name_plural': 'Барааны төлөв',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=50, verbose_name='Барааны нэр')),
                ('zCode', models.IntegerField(blank=True, null=True, verbose_name='Зураасан код')),
                ('zzCode', models.IntegerField(blank=True, null=True, verbose_name='Нэмэлт зураасан код')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Үнэ')),
                ('hemNegj', models.IntegerField(blank=True, null=True, verbose_name='Хэмжих нэгж')),
                ('hudNegj', models.IntegerField(blank=True, null=True, verbose_name='Худалдан авалтын нэгж')),
                ('erNershil', models.CharField(max_length=50, verbose_name='Ерөнхий нэршил')),
                ('emHelber', models.CharField(max_length=50, verbose_name='Эмийн хэлбэр')),
                ('paiz', models.CharField(max_length=50, verbose_name='Пайз')),
                ('uildwerlegch', models.CharField(max_length=50, verbose_name='Үйлдвэрлэгч')),
                ('uNiiluulegch', models.CharField(max_length=50, verbose_name='Үндсэн нийлүүлэгч')),
                ('borBoloh', models.CharField(max_length=50, verbose_name='Борлуулж болох')),
                ('hudAwch', models.CharField(max_length=50, verbose_name='Худалдан авч болох')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.company')),
                ('prodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.prodtype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.state')),
            ],
            options={
                'verbose_name': 'Бараа',
                'verbose_name_plural': 'Бараа',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Харилцагчийн нэр')),
                ('code', models.CharField(max_length=30, verbose_name='Харилцагчийн код')),
                ('mail', models.CharField(max_length=50, verbose_name='Компаний майл')),
                ('password', models.CharField(max_length=50, verbose_name='Майлын нууц үг')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.company')),
            ],
            options={
                'verbose_name': 'Харилцагч',
                'verbose_name_plural': 'Харилцагч',
            },
        ),
    ]
