# Generated by Django 3.1.2 on 2021-05-19 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comName', models.CharField(max_length=50, verbose_name='Компаний нэр')),
                ('mail', models.CharField(max_length=50, verbose_name='Компаний майл')),
                ('password', models.CharField(max_length=50, verbose_name='Майлын нууц үг')),
                ('password2', models.CharField(max_length=50, verbose_name='Майлын нууц үг давтах')),
            ],
            options={
                'verbose_name': 'Компани',
                'verbose_name_plural': 'Компани',
            },
        ),
        migrations.CreateModel(
            name='Hereglegch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Хэрэглэгчийн нэр')),
                ('code', models.CharField(max_length=30, verbose_name='Хэрэглэгчийн код')),
            ],
            options={
                'verbose_name': 'Хэрэглэгч',
                'verbose_name_plural': 'Хэрэглэгч',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50, verbose_name='Барааны нэр')),
                ('zCode', models.IntegerField(blank=True, null=True, verbose_name='Зураасан код')),
                ('pType', models.IntegerField(blank=True, null=True, verbose_name='Барааны төрөл')),
                ('zzCode', models.IntegerField(blank=True, null=True, verbose_name='Нэмэлт зураасан код')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Үнэ')),
                ('hemNegj', models.IntegerField(blank=True, null=True, verbose_name='Хэмжих нэгж')),
                ('hudNegj', models.IntegerField(blank=True, null=True, verbose_name='Худалдан авалтын нэгж')),
                ('erNershil', models.CharField(max_length=50, verbose_name='Ерөнхий нэршил')),
                ('emHelber', models.CharField(max_length=50, verbose_name='Эмийн хэлбэр')),
                ('paiz', models.CharField(max_length=50, verbose_name='Пайз')),
                ('uildwerlegch', models.CharField(max_length=50, verbose_name='Үйлдвэрлэгч')),
                ('uNiiluulegch', models.CharField(max_length=50, verbose_name='Үндсэн нийлүүлэгч')),
                ('category', models.CharField(max_length=50, verbose_name='Дотоод ангилал')),
                ('borBoloh', models.CharField(max_length=50, verbose_name='Борлуулж болох')),
                ('hudAwch', models.CharField(max_length=50, verbose_name='Худалдан авч болох')),
                ('state', models.IntegerField(blank=True, null=True, verbose_name='Төлөв')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BM.company')),
            ],
            options={
                'verbose_name': 'Бараа',
                'verbose_name_plural': 'Бараа',
            },
        ),
    ]
